Update Meeting-Summaries.txt
bananabajanana/Routing-Scheme pull request #4
Opened 2024-03-15 09:41 UTC by oriKatzir

updated meeting 4

2024-03-17 21:58 UTC, bananabajanana requested changes
Please fix the problems :)

2024-03-17 21:58 UTC, bananabajanana commented on Meeting-Summaries.txt
> +* We informed Liam about the project requirements Areiel Rot dissmissed us from and that Liam is incharge with grwading our project.
Spelling mistake in the word "grading"

2024-03-18 06:16 UTC, oriKatzir commented on Meeting-Summaries.txt
> +* We informed Liam about the project requirements Areiel Rot dissmissed us from and that Liam is incharge with grwading our project.
Done boss 👍

2024-03-24 18:32 UTC, bananabajanana reviewed
Good Job !

2024-03-24 18:33 UTC, bananabajanana approved these changes
good job!

2024-03-24 18:33 UTC, merged